### ISSUE TITLE
有朋友有v3.9.2.26版本微信么？分享下，项目里没找到，谢谢

### ISSUE THREAD

**Issue by goldcome** [tom-snow/wechat-windows-versions#16]
有朋友有v3.9.2.26版本微信么？分享下，项目里没找到，谢谢

**Comment by cynen** [comment]
#15 这里有

**Comment by goldcome** [comment]
> #15 这里有

感谢，之前我也搜到过，不过访问不了，刚刚用代理试下了，可以下载了，真是神奇，既然要开代理

**Comment by cynen** [comment]
(这是来自QQ邮箱自动回复邮件。)
 
您好，你的邮件我已经收到。我会在近期尽快给您回复。
