### ISSUE TITLE
无法登陆 提示版本低

### ISSUE THREAD

**Issue by YaleYzF** [tom-snow/wechat-windows-versions#18]
安装3.95版本直接提示版本低  无法登陆 让更新最新版本
有没有解决问题的方法  想用395版本的锁定微信功能  后续最新版本没锁定功能了

**Comment by tom-snow** [comment]
你可以尝试使用 cheat engine (ce) 来在微信的内存中搜索微信的版本号（绿色部分），并将其尝试修改成新的版本号。

微信版本号计算器：https://tom-snow.github.io/wechat-windows-versions/

第一个输入具体版本号，比如： 3.90.2.8 (可能不存在这个版本号，杜撰的）
然后点转换按钮，然后用 ce 来搜索 int 版本号，并且替换。

不清楚较新版本的 wechat 能否使用这个方法，自行测试。

**Comment by wxhbts** [comment]
> 你可以尝试使用 cheat engine (ce) 来在微信的内存中搜索微信的版本号（绿色部分），并将其尝试修改成新的版本号。
> 
> 微信版本号计算器：https://tom-snow.github.io/wechat-windows-versions/
> 
> 第一个输入具体版本号，比如： 3.90.2.8 (可能不存在这个版本号，杜撰的） 然后点转换按钮，然后用 ce 来搜索 int 版本号，并且替换。
> 
> 不清楚较新版本的 wechat 能否使用这个方法，自行测试。

转换不了3.9.12.17

**Comment by tom-snow** [comment]
> 转换不了3.9.12.17

应该已经修复，未测试，如未修复欢迎 reopen 本 issue 反馈
