### ISSUE TITLE
大佬们有3.9.0.22版本嘛

### ISSUE THREAD

**Issue by Ezj-Amon** [tom-snow/wechat-windows-versions#5]
没找到这个版本

**Comment by tom-snow** [comment]
没找到的话可以看看 readme 里使用 web.archive.org 看看微信官网的历史记录有没有，还有其他类似 web archive 的网站也可以去看看，还是没有的话就完全没有了，看看还有什么有缘人保存了那个版本（非 web archive 或者类似网站保存的【比如网盘链接保存的】我这里不会考虑加入 release 里，但是可以发网盘链接在这）

**Comment by bordtown** [comment]
https://www.aliyundrive.com/s/JNNcxPYtWna
提取码97yh
刚好有这个版本
