### ISSUE TITLE
包括3.8.1.26还有之后的版本 图片不会自动下载 有解决办法吗？

### ISSUE THREAD

**Issue by bordtown** [tom-snow/wechat-windows-versions#6]
用之前的版本 发来的图片都是直接就可以另存为，之后的版本 需要先点开图片让他加载完才可以另存，除了降版本，有没有大佬知道解决办法？

**Comment by tom-snow** [comment]
https://github.com/ttttupup/wxhelper

不知道能不能用，自己试试

**Comment by bordtown** [comment]
答非所问 还这么快给我关了

**Comment by tom-snow** [comment]
用 hook 打开图片自动下载这意思还不够明显是吗
