### ISSUE TITLE
微信有64位版本了

### ISSUE THREAD

**Issue by SpecterShell** [tom-snow/wechat-windows-versions#7]
<https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe>
这个安装包现在是纯64位版本的。
<https://dldir1.qq.com/weixin/Windows/WeChatSetup_x86.exe>
这个是纯32位的，版本号不一样。

**Comment by tom-snow** [comment]
要在现有的代码上改动使其同时记录 x64 和 x86 两种版本的会比较麻烦，最简单的方法是新建一个仓库来专门记录 x86 版本的 wechat

**Comment by tom-snow** [comment]
https://github.com/tom-snow/wechat-windows-versions-x86
