### ISSUE TITLE
w10 3.9.2.23 微信DLL注入器V1.0.3显示注入成功，python3.9运行tcpserver.py文件后没有任何消息打印

### ISSUE THREAD

**Issue by Yuri2** [tom-snow/wechat-windows-versions#8]
w10 
微信3.9.2.23 
微信DLL注入器V1.0.3显示注入成功，
python3.9运行tcpserver.py文件后没有任何消息打印，也没有报错
tcpserver.py代码内容：：
`import json
import threading
import socketserver

class ReceiveMsgSocketServer(socketserver.BaseRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def handle(self):
        conn = self.request
        while True:
            try:
                ptr_data = b""
                while True:
                    data = conn.recv(1024)
                    ptr_data += data
                    if len(data) == 0 or data[-1] == 0xA:
                        break

                msg = json.loads(ptr_data)
                ReceiveMsgSocketServer.msg_callback(msg)

            except OSError:
                print(12)
                break
            except json.JSONDecodeError:
                print(34)
                pass
            conn.sendall("200 OK".encode())
        conn.close()

    @staticmethod
    def msg_callback(msg):
        print(56)
        print(msg)

def start_socket_server(port: int = 19099,
                        request_handler=ReceiveMsgSocketServer,
                        main_thread: bool = True) -> int or None:
    ip_port = ("127.0.0.1", port)
    try:
        s = socketserver.ThreadingTCPServer(ip_port, request_handler)
        if main_thread:
            s.serve_forever()
        else:
            socket_server = threading.Thread(target=s.serve_forever)
            socket_server.setDaemon(True)
            socket_server.start()
            return socket_server.ident
    except KeyboardInterrupt:
        print(67)
        pass
    except Exception as e:
        print(e)
    return None

if __name__ == '__main__':
    start_socket_server()
`

**Comment by Yuri2** [comment]
交流飞机群也加不了

**Comment by P3R5T7U9** [comment]
近期在Github上找PC端微信历史版本收集仓库，才翻到这个仓库，继而在Issue区看到老哥你这条Issue，不知老哥你当初提到“微信DLL注入器”是Github上还是吾爱论坛上哪位大佬制作？？

麻烦老哥回复甩下你提到“微信DLL注入器”原发布地址，近期也在找相关注入器工具
